### ISSUE TITLE
Use standard VGA 640x480 instead of PAL 720x576 by default

### ISSUE THREAD

**Issue by mcclure** [sporniket/the-cradle-colorlight-i9-ecp5-amaranth-hdl#10]
Not sure if it's best to relay this information here, on Matrix or elsewhere but—

Got branch `7-does-not-appear-to-build-on-windows` built and programmed. The light blinks. However, when I plugged it into a spare Samsung HDMI monitor, I did not see the blinking as expected. The HDMI monitor does react, but it oscillates between a black and a different black with a icon in the top left as if the monitor is rapidly gaining and losing signal. The blink pattern is erratic and not the same as the LED blink rate.

Is this surprising?

https://mastodon.social/@mcc/111155360337843136

**Comment by sporniket** [comment]
The first thing that comes to mind is the video mode that I selected : 720x576 pixels at 50 Hz (Standard Definition, PAL), and maybe this mode is not supported by all screen ?

However I had prepared another setting for the pll and orchestrator to have a regular VGA 640x480 ; in `the-cradle.py` : https://github.com/sporniket/the-cradle-colorlight-i9-ecp5-amaranth-hdl/blob/main/src/the_cradle/the_cradle.py#L38-L39

you can try with importing the setting from `.vid_settings_640x480_59Hz94` instead of `.vid_settings_720x576_50Hz`, maybe you will have more luck with your monitor ?

(my monitor could use both settings)

**Comment by mcclure** [comment]
In 640x480 it works!! Thanks so much. Now that I have a successful test I think I can make any future changes myself.

Video: https://mastodon.social/@mcc/111156530447699355

**Comment by sporniket** [comment]
Great !

Good to know that the default screen mode I selected is potentially not supported everywere.

I will change to the more standard mode then.
